### ISSUE TITLE
Enable user to add free parameters

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#124] opened 2018-11-06 22:13 UTC
Though the bvp solvers can handle unknown parameters, there is no way for the user to add them in an input file. If I am missing something and this is already in there, let me know, but I am going to try and put in ocp.parameter method.

**Comment by msparapa** [comment] 2018-11-06 22:43
Sounds good. I ran into this exact issue when trying to implement the time optimal rocket launch problem, though I don't remember the exact quantity I was dealing with.

When implementing this, assume all parameters defined by the user are `dynamical_parameters` from `bvpsol/Solution.py`. Then the actual bvp solvers shouldn't have a problem regardless of the parameter type. We can implement the nondynamical type at a later date since they are not as generalized but faster.

**Comment by msparapa** [comment] 2018-11-09 17:50
As a result of working on #112, I removed the `SymVar` class from `problem.py`. In my opinion, it's easier to work with stuff in `optimlib` now, despite there being more variables and operations floating around. This change probably will impact some of the work here with free parameters so I just wanted to give you a heads up.

**Comment by msparapa** [comment] 2018-11-13 18:30
@SeanMatthewNolan how are you coming along with this? Do you have an example problem that needs this feature? I can help out implementing this.

**Comment by SeanMatthewNolan** [comment] 2018-11-13 18:38
I was pretty close last week, but life got in the way, and I'm trying to get back to finishing it. I wanted it now as an intermediate toward #123 and a workaround. Technically, I know how to implement, but it's a bit tedious. If you want to help, feel free, but you don't have to

**Comment by msparapa** [comment] 2018-11-13 20:35
I see. Have you pushed the latest changes to your I124 branch? I can take over and finish it up.

**Comment by msparapa** [comment] 2018-11-19 18:32
I took what you did for parameters and added in some of the recent changes to the solver, then merged them in. I left out what you did with the Lagrange multipliers for the parameters for the time being because I wasn't able to figure out what the issue was causing the singular matrices. So parameters work fine as long as they are not a part of the cost functions. We get the expected result where the problem is underconstrained since there's an additional parameter but no extra boundary condition so it forces Shooting to use the least squares method instead of directly solving the linear system.

**Comment by SeanMatthewNolan** [comment] 2018-11-26 23:07
I figured out my error with the coparameters that ended making the singular matrices. The parameters are constant, but the coparameters are not. I'll implement them in the next hour.

**Comment by SeanMatthewNolan** [comment] 2018-11-27 00:17
The complete functionality is added to the traditional and icrm methods. I pushed the changes to the master. The guess generator doesn't work unless the costate_guess is specified explicitly to contain coparameters to. It didn't appear to be a straight-forward change, so I will add another issue for it. The guess generator needs revamping anyway. I'll leave it to @msparapa to add it to diffyg, then we can close this issue. The coparameters should be treated nearly identically to costates, i.e. coparameter_rate = -dH/dp.

**Comment by msparapa** [comment] 2018-11-27 14:30
Cool! As a part of #126 I added a "solution_mapper" output to `optimlib`. I think I'll add one "mapper" and one inverse "mapper". What these do is take a normal solution the user might interact with and translates it to whatever format is output from `optimlib`. My idea is this could handle formatting the guesses correctly for path constraints, reduction, etc while the guess generator stays intuitive for the designer. Would probably be good to go through the guess generator thoroughly and make sure we both get features we want in there.

**Closed as completed** 2018-11-29 04:35 UTC
Labels: enhancement
